### ISSUE TITLE
Request to chat

### ISSUE THREAD

**Issue by KaitaniLabs** [bbrk24/lexifer-ts#2]
Hi, I'm building a collaborative world-building software and community and I would really like to include a conlang element similar to your version of the Lexifer. Would you be interested in chatting about it?

Regards

**Comment by bbrk24** [comment]
I don't really get why you're asking. This isn't the first implementation of it (see [wmannis/lexifer](https://github.com/wmannis/lexifer)), though it does have more features than what it's based on. If you want to write your own, be my guest. If you want to use this directly, it's available on npm as [`lexifer`](https://www.npmjs.com/package/lexifer). If you'd like me to add or change something so that you can use it, please file a separate issue for that.
